/**
 * HTML Builder
 *
 * Generates a self-contained HTML document with D3.js rendering,
 * WebSocket live refresh, zoom/pan, hover tooltips, dirty highlighting,
 * and tabbed flow navigation matching the Node-RED editor interface.
 *
 * @module renderer/html-builder
 */

import { JUNCTION_STYLE } from './colors.js';

/**
 * Default node dimensions if not specified in raw flow data.
 */
const DEFAULT_W = 100;
const DEFAULT_H = 30;

/**
 * Color map for embedding in the HTML (subset of most common types).
 */
const COLOR_MAP = {
  'inject': '#a6bbcf', 'debug': '#87a980', 'function': '#fdd0a2',
  'switch': '#d8bfd8', 'change': '#e2d6b8', 'range': '#d8bfd8',
  'template': '#d8bfd8', 'delay': '#fdd0a2', 'trigger': '#fdd0a2',
  'exec': '#fdd0a2', 'complete': '#c0c0c0', 'catch': '#c0c0c0',
  'status': '#c0c0c0', 'comment': '#ffffff', 'unknown': '#c0c0c0',
  'link in': '#c0c0c0', 'link out': '#c0c0c0', 'link call': '#c0c0c0',
  'mqtt in': '#d8bfd8', 'mqtt out': '#d8bfd8',
  'http in': '#d8bfd8', 'http response': '#d8bfd8', 'http request': '#e2d6b8',
  'split': '#d8bfd8', 'join': '#d8bfd8', 'batch': '#d8bfd8', 'sort': '#d8bfd8',
  'csv': '#d8bfd8', 'html': '#d8bfd8', 'json': '#d8bfd8', 'xml': '#d8bfd8', 'yaml': '#d8bfd8',
  'file in': '#87a980', 'file out': '#87a980', 'file': '#87a980', 'watch': '#87a980',
  'rbe': '#fdd0a2', 'ui_button': '#d8bfd8', 'ui_text': '#d8bfd8',
  'ui_gauge': '#d8bfd8', 'ui_chart': '#d8bfd8',
};

/**
 * Build a self-contained HTML document string that renders the staging workspace
 * with a tab bar for multiple flows.
 *
 * @param {object[]} flows - Raw Node-RED flows array (from StagingStore)
 * @param {object} options - Rendering options
 * @param {boolean} [options.highlightDirty=true] - Highlight un-deployed nodes
 * @param {Set<string>} [options.dirtyNodeIds] - Set of dirty node IDs
 * @returns {string} Complete HTML document
 */
export function buildHTML(flows, options = {}) {
  const {
    highlightDirty = true,
    dirtyNodeIds = new Set(),
  } = options;

  const dirtyArr = [...dirtyNodeIds];
  // Escape newlines and other control characters for safe embedding in HTML <script>
  // Also escape </ sequences to prevent premature script tag closure (e.g., if
  // function node code contains </script> or </body> etc.)
  const flowsJSON = JSON.stringify(flows)
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t')
    .replace(/<\//g, '<\\/');
  const colorMapJSON = JSON.stringify(COLOR_MAP).replace(/<\//g, '<\\/');
  const dirtyNodeIdsJSON = JSON.stringify(dirtyArr);
  const hd = highlightDirty;

  // The HTML template is built as a regular string concatenation to avoid
  // template-literal escaping issues with the embedded JavaScript code.
  const html = [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '<title>Node-RED Staging Preview</title>',
    '<script src="https://d3js.org/d3.v7.min.js"></script>',
    '<style>',
    '  * { margin: 0; padding: 0; box-sizing: border-box; }',
    '  body { overflow: hidden; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }',
    '  #tab-bar {',
    '    position: fixed; top: 0; left: 0; right: 0; height: 34px;',
    '    background: #e0e0e0; z-index: 1001;',
    '    display: flex; overflow-x: auto; overflow-y: hidden;',
    '    white-space: nowrap; padding: 0; margin: 0;',
    '    border-bottom: 1px solid #bbb;',
    '    box-shadow: 0 1px 3px rgba(0,0,0,0.08);',
    '  }',
    '  #tab-bar::-webkit-scrollbar { height: 4px; }',
    '  #tab-bar::-webkit-scrollbar-thumb { background: #aaa; border-radius: 2px; }',
    '  #tab-bar-actions { margin-left: auto; flex-shrink: 0; display: flex; align-items: center; padding: 0 8px; border-left: 1px solid #ccc; background: #e0e0e0; }',
    '  #btn-refresh { display: inline-flex; align-items: center; gap: 5px; padding: 3px 10px; font-size: 11px; cursor: pointer; background: #fff; border: 1px solid #bbb; border-radius: 3px; color: #444; user-select: none; transition: background 0.15s; }',
    '  #btn-refresh:hover { background: #f0f0f0; }',
    '  #btn-refresh:active { background: #e4e4e4; }',
    '  #btn-refresh.loading { opacity: 0.6; pointer-events: none; }',
    '  #btn-refresh .icon { display: inline-block; transition: transform 0.5s; }',
    '  #btn-refresh.loading .icon { animation: spin 0.7s linear infinite; }',
    '  @keyframes spin { to { transform: rotate(360deg); } }',
    '  .nr-tab {',
    '    display: inline-flex; align-items: center;',
    '    padding: 0 18px; cursor: pointer; font-size: 12px;',
    '    color: #555; border-right: 1px solid #ccc;',
    '    user-select: none; flex-shrink: 0; height: 100%;',
    '    transition: background 0.15s;',
    '  }',
    '  .nr-tab.active {',
    '    background: #fff; color: #333; font-weight: 600;',
    '    box-shadow: inset 0 -2px 0 #c72;',
    '  }',
    '  .nr-tab:hover:not(.active) { background: #d6d6d6; }',
    '  .nr-tab.dirty::after {',
    "    content: '\u25cf'; font-size: 8px; color: #ff8c00;",
    '    margin-left: 6px; line-height: 1;',
    '  }',    '  .nr-tab-close {',
    '    display: inline-flex; align-items: center; justify-content: center;',
    '    margin-left: 8px; width: 16px; height: 16px; border-radius: 3px;',
    '    font-size: 13px; line-height: 1; cursor: pointer; color: #888;',
    '    transition: background 0.15s, color 0.15s;',
    '  }',
    '  .nr-tab-close:hover { background: #ccc; color: #333; }',    '  #canvas-wrap { position: fixed; top: 0; left: 0; right: 0; bottom: 0; }',
    '  #canvas-wrap.with-tabs { top: 34px; }',
    '  #canvas { width: 100%; height: 100%; cursor: grab; }',
    '  #canvas:active { cursor: grabbing; }',
    '  #banner {',
    '    display: none; position: fixed; top: 0; left: 0; right: 0;',
    '    background: #fff3cd; color: #856404; text-align: center;',
    '    padding: 5px 12px; font-size: 12px; z-index: 2000;',
    '    border-bottom: 1px solid #ffc107;',
    '  }',
    '  #banner.visible { display: block; }',
    '  .nr-node { cursor: pointer; transition: filter 0.2s; }',
    '  .nr-node:hover { filter: brightness(1.1); }',
    '  .nr-node-dirty .nr-node-body { stroke: #ff8c00; stroke-width: 2.5; }',
    '  .nr-node-disabled .nr-node-body { stroke-dasharray: 5 5; opacity: 0.5; }',
    '  .nr-link { fill: none; stroke: #999; stroke-width: 1.5; }',
    '  .nr-link-disabled { stroke: #ccc; stroke-dasharray: 4 2; }',
    '  .nr-group-rect { fill: none; stroke: #999; stroke-dasharray: 5 3; stroke-opacity: 0.5; }',
    '  .nr-tooltip {',
    '    position: fixed; pointer-events: none; z-index: 999;',
    '    background: rgba(0,0,0,0.85); color: #fff; padding: 8px 12px;',
    '    border-radius: 6px; font-size: 12px; line-height: 1.5;',
    '    max-width: 260px; white-space: normal;',
    '  }',
    '  .nr-tooltip .tt-name { font-weight: bold; font-size: 13px; }',
    '  .nr-tooltip .tt-dirty { color: #ff8c00; }',
    '  .nr-legend {',
    '    position: fixed; bottom: 12px; left: 12px; z-index: 500;',
    '    background: rgba(255,255,255,0.9); border: 1px solid #ccc;',
    '    border-radius: 6px; padding: 6px 12px; font-size: 11px; color: #666;',
    '  }',
    '  .nr-empty {',
    '    position: absolute; top: 50%; left: 50%; transform: translate(-50%,-50%);',
    '    color: #aaa; font-size: 14px; text-align: center; pointer-events: none;',
    '  }',
    '  .nr-subflow-badge { pointer-events: none; }',
    '  .nr-subflow-badge-label { pointer-events: none; }',
    '</style>',
    '</head>',
    '<body>',
    '<div id="banner">\u26a0\ufe0f Disconnected \u2014 retrying\u2026</div>',
    '<div id="tab-bar"><div id="tab-bar-actions"><button id="btn-refresh"><span class="icon">&#x21bb;</span> Refresh</button></div></div>',
    '<div id="canvas-wrap">',
    '  <div id="canvas"></div>',
    '</div>',
    '<div class="nr-legend" id="legend" style="display:none">\ud83d\udfe0 Orange border = Un-deployed changes</div>',
    '<div class="nr-tooltip" id="tooltip" style="display:none"></div>',
    '',
    '<script>',
    'var ALL_FLOWS = ' + flowsJSON + ';',
    'var DIRTY_NODE_IDS = new Set(' + dirtyNodeIdsJSON + ');',
    'var HIGHLIGHT_DIRTY = ' + hd + ';',
    'var COLOR_MAP = ' + colorMapJSON + ';',
    'var DEFAULT_COLOR = "#cccccc";',
    'var DEFAULT_W = ' + DEFAULT_W + ';',
    'var DEFAULT_H = ' + DEFAULT_H + ';',
    '',
    '(function() {',
    '  var banner = document.getElementById("banner");',
    '  var tooltip = document.getElementById("tooltip");',
    '  var legend = document.getElementById("legend");',
    '  var tabBar = document.getElementById("tab-bar");',
    '  var btnRefresh = document.getElementById("btn-refresh");',
    '  var canvasWrap = document.getElementById("canvas-wrap");',
    '  var canvasEl = document.getElementById("canvas");',
    '',
    '  function extractTabs(flows) {',
    '    return flows.filter(function(n) { return n.type === "tab"; })',
    '      .map(function(t) { return { id: t.id, name: t.label || t.name || t.id, disabled: t.d === true, kind: "tab" }; });',
    '  }',
    '',
    '  function buildTabData(flows, tabId, dirtySet) {',
    '    var tabNodes = flows.filter(function(n) {',
    '      return n.z === tabId && n.type !== "tab" && n.type !== "group"',
    '        && Array.isArray(n.wires);',
    '    });',
    '    var tabGroups = flows.filter(function(n) {',
    '      return n.z === tabId && n.type === "group";',
    '    });',
    '    var nodeIdSet = new Set(tabNodes.map(function(n) { return n.id; }));',
    '    var nodes = tabNodes.map(function(n) {',
    '      var isJunction = n.type === "junction";',
    '      var outs = n.outputs != null ? n.outputs : (Array.isArray(n.wires) ? n.wires.length : 0);',
    '      var ins = n.inputs != null ? n.inputs : 0;',
    '      var portH = Math.max(outs, ins, 1) * 13 + 8;',
    '      var nodeH = Math.max(n.h || DEFAULT_H, portH);',
    '      return {',
    '        id: n.id, type: n.type, name: getSubflowInstanceName(n),',
    '        x: n.x || 0, y: n.y || 0, w: isJunction ? ' + (JUNCTION_STYLE.radius * 2) + ' : (n.w || DEFAULT_W), h: isJunction ? ' + (JUNCTION_STYLE.radius * 2) + ' : nodeH,',
    '        inputs: ins,',
    '        outputs: outs,',
    '        d: n.d === true,',
    '        dirty: HIGHLIGHT_DIRTY ? dirtySet.has(n.id) : false,',
    '        wires: n.wires || [],',
    '        isJunction: isJunction',
    '      };',
    '    });',
    '    var groups = tabGroups.map(function(g) {',
    '      return {',
    '        id: g.id, name: g.name || "Group",',
    '        x: g.x || 0, y: g.y || 0, w: g.w || 40, h: g.h || 40,',
    '        style: g.style || {},',
    '        nodes: (g.nodes || []).filter(function(mid) { return nodeIdSet.has(mid); })',
    '      };',
    '    });',
    '    var links = [];',
    '    for (var i = 0; i < nodes.length; i++) {',
    '      var node = nodes[i];',
    '      if (!node.wires || node.wires.length === 0) continue;',
    '      node.wires.forEach(function(targets, portIndex) {',
    '        if (!Array.isArray(targets)) return;',
    '        for (var j = 0; j < targets.length; j++) {',
    '          var tn = nodes.find(function(n) { return n.id === targets[j]; });',
    '          if (tn) links.push({ source: node, sourcePort: portIndex, target: tn });',
    '        }',
    '      });',
    '    }',
    '    var bb = computeBBox(nodes, groups);',
    '    return { nodes: nodes, groups: groups, links: links, bb: bb };',
    '  }',
    '',
    '  function computeBBox(nodes, groups) {',
    '    if (nodes.length === 0 && groups.length === 0) {',
    '      return { minX: 0, minY: 0, maxX: 400, maxY: 200, width: 400, height: 200 };',
    '    }',
    '    var minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;',
    '    for (var i = 0; i < nodes.length; i++) {',
    '      var n = nodes[i];',
    '      if (n.x - n.w/2 < minX) minX = n.x - n.w/2;',
    '      if (n.x + n.w/2 > maxX) maxX = n.x + n.w/2;',
    '      if (n.y - n.h/2 < minY) minY = n.y - n.h/2;',
    '      if (n.y + n.h/2 > maxY) maxY = n.y + n.h/2;',
    '    }',
    '    for (var j = 0; j < groups.length; j++) {',
    '      var g = groups[j];',
    '      if (g.x < minX) minX = g.x;',
    '      if (g.y < minY) minY = g.y;',
    '      if (g.x + g.w > maxX) maxX = g.x + g.w;',
    '      if (g.y + g.h > maxY) maxY = g.y + g.h;',
    '    }',
    '    var p = 30;',
    '    return {',
    '      minX: minX - p, minY: minY - p, maxX: maxX + p, maxY: maxY + p,',
    '      width: maxX - minX + 2*p, height: maxY - minY + 2*p',
    '    };',
    '  }',
    '',
    '  function getNodeColor(type) {',
    '    if (typeof type === "string" && type.startsWith("subflow:")) return "#9BC7D4";',
    '    return COLOR_MAP[type] || DEFAULT_COLOR;',
    '  }',
    '',
    '  function getNodeCSSClass(d) {',
    '    var c = "nr-node";',
    '    if (d.dirty) c += " nr-node-dirty";',
    '    if (d.d) c += " nr-node-disabled";',
    '    if (d.type && d.type.startsWith("subflow:")) c += " subflow-instance";',
    '    return c;',
    '  }',
    '',
    '  function generateLinkPath(origX, origY, destX, destY, sc) {',
    '    var dy = destY - origY, dx = destX - origX;',
    '    var delta = Math.sqrt(dy*dy + dx*dx);',
    '    var NODE_W = DEFAULT_W;',
    '    var NODE_H = DEFAULT_H;',
    '    // Always exit right from source, enter left from target',
    '    var dSign = (dx >= 0) ? 1 : -1;',
    '    var scale = 0.75;',
    '    if (Math.abs(dx) < NODE_W) {',
    '      scale = 0.75 - 0.75 * ((NODE_W - Math.abs(dx)) / NODE_W);',
    '    } else if (dx < 0) {',
    '      scale = 0.4 - 0.2 * (Math.max(0, (NODE_W - Math.min(Math.abs(dx), Math.abs(dy))) / NODE_W));',
    '    }',
    '    // Control points: first goes right, second comes from left',
    '    var cp0x = origX + NODE_W * scale;',
    '    var cp1x = destX - NODE_W * scale;',
    '    if (dx < 0 && Math.abs(dy) > NODE_H) {',
    '      // Vertical L-shaped routing for stacked nodes',
    '      var midY = (origY + destY) / 2;',
    '      return "M " + origX + " " + origY + " C " + cp0x + " " + origY + " " + cp0x + " " + midY + " " + (origX+destX)/2 + " " + midY +',
    '        " L " + (origX+destX)/2 + " " + midY + " C " + cp1x + " " + midY + " " + cp1x + " " + destY + " " + destX + " " + destY;',
    '    }',
    '    // Standard horizontal S-curve: exit right, enter left',
    '    return "M " + origX + " " + origY + " C " + cp0x + " " + origY + " " + cp1x + " " + destY + " " + destX + " " + destY;',
    '  }',
    '',
    '  function escapeHtml(str) {',
    '    var d = document.createElement("div");',
    '    d.textContent = str || "";',
    '    return d.innerHTML;',
    '  }',
    '',
    '  function getSubflowInstanceName(n) {',
    '    if (n.name) return n.name;',
    '    if (typeof n.type === "string" && n.type.startsWith("subflow:")) {',
    '      var defId = n.type.slice("subflow:".length);',
    '      for (var i = 0; i < ALL_FLOWS.length; i++) {',
    '        var f = ALL_FLOWS[i];',
    '        if (f.type === "subflow" && f.id === defId && f.name) return f.name;',
    '      }',
    '    }',
    '    return n.type;',
    '  }',
    '',
    '  function resolveSubflowDef(defId) {',
    '    for (var i = 0; i < ALL_FLOWS.length; i++) {',
    '      var f = ALL_FLOWS[i];',
    '      if (f.type === "subflow" && f.id === defId) return f;',
    '    }',
    '    return null;',
    '  }',
    '',
    '  function reconcileTabs(freshRegularTabs) {',
    '    tabs = tabs.filter(function(t) {',
    '      if (t.kind !== "subflow") return true;',
    '      return resolveSubflowDef(t.id) !== null;',
    '    });',
    '    var freshMap = {};',
    '    for (var i = 0; i < freshRegularTabs.length; i++) {',
    '      var ft = freshRegularTabs[i];',
    '      freshMap[ft.id] = ft;',
    '    }',
    '    for (var j = tabs.length - 1; j >= 0; j--) {',
    '      var t = tabs[j];',
    '      if (t.kind === "subflow") continue;',
    '      if (freshMap[t.id]) {',
    '        t.name = freshMap[t.id].name;',
    '        t.disabled = freshMap[t.id].disabled;',
    '        delete freshMap[t.id];',
    '      } else {',
    '        tabs.splice(j, 1);',
    '      }',
    '    }',
    '    for (var id in freshMap) {',
    '      if (Object.prototype.hasOwnProperty.call(freshMap, id)) {',
    '        tabs.push(freshMap[id]);',
    '      }',
    '    }',
    '  }',
    '',
    '  function openSubflowTab(defId) {',
    '    var def = resolveSubflowDef(defId);',
    '    if (!def) return;',
    '    for (var i = 0; i < tabs.length; i++) {',
    '      if (tabs[i].id === defId && tabs[i].kind === "subflow") {',
    '        switchTab(defId);',
    '        return;',
    '      }',
    '    }',
    '    var activeIdx = -1;',
    '    for (var j = 0; j < tabs.length; j++) {',
    '      if (tabs[j].id === currentTabId) { activeIdx = j; break; }',
    '    }',
    '    var newEntry = {',
    '      id: defId,',
    '      name: def.name || defId,',
    '      disabled: false,',
    '      kind: "subflow"',
    '    };',
    '    if (activeIdx >= 0) {',
    '      tabs.splice(activeIdx + 1, 0, newEntry);',
    '    } else {',
    '      tabs.push(newEntry);',
    '    }',
    '    buildTabBar();',
    '    switchTab(defId);',
    '  }',
    '',
    '  function closeSubflowTab(id) {',
    '    for (var i = 0; i < tabs.length; i++) {',
    '      if (tabs[i].id === id && tabs[i].kind === "subflow") {',
    '        tabs.splice(i, 1);',
    '        delete zoomState[id];',
    '        break;',
    '      }',
    '    }',
    '    buildTabBar();',
    '    if (currentTabId === id) {',
    '      if (tabs.length > 0) {',
    '        switchTab(tabs[Math.max(0, tabs.length - 1)].id);',
    '      } else {',
    '        currentTabId = "__empty__";',
    '        groupLayer.selectAll("*").remove();',
    '        linkLayer.selectAll("*").remove();',
    '        nodeLayer.selectAll("*").remove();',
    '        emptyLabel.style("display", "block");',
    '        svg.call(zoom.transform, d3.zoomIdentity);',
    '      }',
    '    } else {',
    '      refreshTabDirtyIndicators();',
    '    }',
    '  }',
    '',
    '  // ---- Tab state ----',
    '  var tabs = extractTabs(ALL_FLOWS);',
    '  var zoomState = {};',
    '  var currentTabId = null;',
    '',
    '  if (tabs.length === 0) {',
    '    var ntn = ALL_FLOWS.filter(function(n) {',
    '      return n.type !== "tab" && n.type !== "group"',
    '        && Array.isArray(n.wires);',
    '    });',
    '    if (ntn.length > 0) {',
    '      tabs = [{ id: ntn[0].z || "__default__", name: "Flow", disabled: false, kind: "tab" }];',
    '    }',
    '  }',
    '',
    '  function buildTabBar() {',
    '    // Remove existing tab elements, keep #tab-bar-actions',
    '    var existing = tabBar.querySelectorAll(".nr-tab");',
    '    for (var k = 0; k < existing.length; k++) { existing[k].remove(); }',
    '    if (tabs.length <= 1) { canvasWrap.classList.remove("with-tabs"); }',
    '    else { canvasWrap.classList.add("with-tabs"); }',
    '    var actions = document.getElementById("tab-bar-actions");',
    '    for (var i = 0; i < tabs.length; i++) {',
    '      var t = tabs[i];',
    '      var el = document.createElement("div");',
    '      el.className = "nr-tab";',
    '      el.textContent = t.name;',
    '      el.setAttribute("data-tab-id", t.id);',
    '      if (t.id === currentTabId) el.classList.add("active");',
    '      if (t.disabled) el.style.opacity = "0.5";',
    '      el.addEventListener("click", function() {',
    '        switchTab(this.getAttribute("data-tab-id"));',
    '      });',
    '      if (t.kind === "subflow") {',
    '        var cls = document.createElement("span");',
    '        cls.className = "nr-tab-close";',
    '        cls.textContent = "\\u00d7";',
    '        cls.addEventListener("click", function(e) {',
    '          e.stopPropagation();',
    '          closeSubflowTab(this.parentNode.getAttribute("data-tab-id"));',
    '        });',
    '        el.appendChild(cls);',
    '      }',
    '      tabBar.insertBefore(el, actions);',
    '    }',
    '  }',
    '',
    '  // ---- D3 setup ----',
    '  var width = canvasEl.clientWidth;',
    '  var height = canvasEl.clientHeight;',
    '  var svg = d3.select("#canvas").append("svg").attr("width", width).attr("height", height);',
    '  var defs = svg.append("defs");',
    '  defs.append("pattern").attr("id", "grid").attr("width", 20).attr("height", 20)',
    '    .attr("patternUnits", "userSpaceOnUse")',
    '    .append("path").attr("d", "M 20 0 L 0 0 0 20")',
    '    .attr("fill", "none").attr("stroke", "#e0e0e0").attr("stroke-width", 0.5);',
    '  var contentGroup = svg.append("g");',
    '  contentGroup.append("rect").attr("width", 8000).attr("height", 8000).attr("fill", "url(#grid)");',
    '  var groupLayer = contentGroup.append("g").attr("class", "group-layer");',
    '  var linkLayer = contentGroup.append("g").attr("class", "link-layer");',
    '  var nodeLayer = contentGroup.append("g").attr("class", "node-layer");',
    '  var emptyLabel = contentGroup.append("text").attr("class", "nr-empty")',
    '    .attr("text-anchor", "middle").text("No nodes in this flow");',
    '',
    '  var zoom = d3.zoom().scaleExtent([0.1, 2]).filter(function(event) {',
    '    // Block plain wheel; allow touch (pinch), mouse drag, and Ctrl+wheel',
    '    if (event.type === "wheel") return event.ctrlKey;',
    '    return true;',
    '  }).on("zoom", function(event) {',
    '    contentGroup.attr("transform", event.transform);',
    '    if (currentTabId) zoomState[currentTabId] = event.transform;',
    '  });',
    '  svg.call(zoom);',
    '  svg.node().addEventListener("wheel", function(event) {',
    '    if (event.ctrlKey) return; // Let d3.zoom handle Ctrl+wheel zoom',
    '    event.preventDefault();',
    '    var t = d3.zoomTransform(svg.node());',
    '    var newX = t.x - event.deltaX;',
    '    var newY = t.y - event.deltaY;',
    '    svg.call(zoom.transform, d3.zoomIdentity.translate(newX, newY).scale(t.k));',
    '  }, {passive: false});',
    '',
    '  function render(data) {',
    '    var nodes = data.nodes, groups = data.groups, links = data.links;',
    '    var hasDirty = nodes.some(function(n) { return n.dirty; });',
    '    legend.style.display = hasDirty ? "block" : "none";',
    '    emptyLabel.style("display", nodes.length === 0 && groups.length === 0 ? "block" : "none");',
    '',
    '    var groupSel = groupLayer.selectAll(".nr-group").data(groups, function(d) { return d.id; });',
    '    groupSel.exit().remove();',
    '    var ge = groupSel.enter().append("g").attr("class", "nr-group");',
    '    ge.append("rect").attr("class", "nr-group-rect").attr("rx", 4).attr("ry", 4);',
    '    ge.append("text").attr("font-size", 10).attr("fill", "#999");',
    '    groupSel.merge(ge).each(function(d) {',
    '      var g = d3.select(this);',
    '      g.select("rect").attr("x", d.x).attr("y", d.y).attr("width", d.w).attr("height", d.h);',
    '      g.select("text").attr("x", d.x + 5).attr("y", d.y + 15).text(d.name || "Group");',
    '    });',
    '',
    '    var linkSel = linkLayer.selectAll(".nr-link")',
    '      .data(links, function(d) { return d.source.id + ":" + d.sourcePort + ":" + d.target.id; });',
    '    linkSel.exit().remove();',
    '    var linkEnter = linkSel.enter().append("path").attr("class", "nr-link");',
    '    linkEnter.merge(linkSel)',
    '      .attr("d", function(d) {',
    '        var no = d.source.outputs || 1;',
    '        var py = -((no - 1) / 2) * 13 + 13 * d.sourcePort;',
    '        return generateLinkPath(d.source.x + d.source.w / 2, d.source.y + py,',
    '          d.target.x - d.target.w / 2, d.target.y, 1);',
    '      })',
    '      .classed("nr-link-disabled", function(d) { return d.source.d || d.target.d; });',
    '',
    '    var nodeSel = nodeLayer.selectAll(".nr-node").data(nodes, function(d) { return d.id; });',
    '    nodeSel.exit().remove();',
    '    var ne = nodeSel.enter().append("g")',
    '      .attr("class", function(d) { return getNodeCSSClass(d); })',
    '      .attr("transform", function(d) {',
    '        if (d.isJunction) return "translate(" + d.x + "," + d.y + ")";',
    '        return "translate(" + (d.x - d.w/2) + "," + (d.y - d.h/2) + ")";',
    '      })',
    '      .on("mouseenter", showTooltip).on("mouseleave", hideTooltip)',
    '      .on("dblclick", handleNodeDblclick);',
    '    // Regular node body (rect + text)',
    '    ne.filter(function(d) { return !d.isJunction; }).append("rect").attr("class", "nr-node-body").attr("rx", 5).attr("ry", 5)',
    '      .attr("fill", function(d) { return getNodeColor(d.type); });',
    '    ne.filter(function(d) { return !d.isJunction; }).append("text").attr("text-anchor", "middle").attr("font-size", 10)',
    '      .attr("fill", "#333").attr("dy", "0.35em");',
    '    // Junction circle (only for junction nodes)',
    '    ne.filter(function(d) { return d.isJunction; }).append("circle")',
    '      .attr("r", ' + JUNCTION_STYLE.radius + ').attr("fill", "' + JUNCTION_STYLE.fill + '").attr("stroke", "' + JUNCTION_STYLE.stroke + '").attr("stroke-width", 1.5);',
    '    nodeSel.merge(ne).each(function(d) {',
    '      var g = d3.select(this);',
    '      g.attr("class", getNodeCSSClass(d));',
    '      if (d.isJunction) {',
    '        g.attr("transform", "translate(" + d.x + "," + d.y + ")");',
    '        return;',
    '      }',
    '      g.attr("transform", "translate(" + (d.x - d.w/2) + "," + (d.y - d.h/2) + ")");',
    '      g.select("rect").attr("width", d.w).attr("height", d.h)',
    '        .attr("fill", getNodeColor(d.type));',
    '      g.select("text").attr("x", d.w/2).attr("y", d.h/2)',
    '        .text((d.name || d.type).substring(0, 20));',
    '      if (d.inputs > 0 && g.select(".nr-port-input").empty()) {',
    '        g.append("rect").attr("class", "nr-port-input")',
    '          .attr("x", -5).attr("y", d.h/2 - 4).attr("width", 8).attr("height", 8)',
    '          .attr("rx", 2).attr("fill", "#999");',
    '      }',
    '      g.selectAll(".nr-port-output").remove();',
    '      for (var i = 0; i < (d.outputs || 0); i++) {',
    '        var py = d.h/2 - ((d.outputs - 1)/2)*13 + 13*i - 4;',
    '        g.append("rect").attr("class", "nr-port-output")',
    '          .attr("x", d.w - 3).attr("y", py).attr("width", 8).attr("height", 8)',
    '          .attr("rx", 2).attr("fill", "#999");',
    '      }',
    '      if (d.type && d.type.startsWith("subflow:") && g.select(".nr-subflow-badge").empty()) {',
    '        g.append("rect").attr("class", "nr-subflow-badge")',
    '          .attr("x", d.w - 18).attr("y", 2).attr("width", 16).attr("height", 12)',
    '          .attr("rx", 2).attr("fill", "#7BA7B3").attr("stroke", "#5A8A96").attr("stroke-width", 0.5);',
    '        g.append("text").attr("class", "nr-subflow-badge-label")',
    '          .attr("x", d.w - 10).attr("y", 11).attr("text-anchor", "middle")',
    '          .attr("font-size", 8).attr("fill", "#fff").attr("font-weight", "bold")',
    '          .text("S");',
    '      }',
    '    });',
    '  }',
    '',
    '  function fitToView(bb) {',
    '    var cw = bb.width || 800, ch = bb.height || 600;',
    '    var s = Math.min(width / cw, height / ch);',
    '    // Clamp: never smaller than 25%, never larger than 100%',
    '    s = Math.max(0.25, Math.min(1.0, s));',
    '    var tx = (width - cw * s) / 2 - (bb.minX || 0) * s;',
    '    var ty = (height - ch * s) / 2 - (bb.minY || 0) * s;',
    '    svg.call(zoom.transform, d3.zoomIdentity.translate(tx, ty).scale(s));',
    '  }',
    '',
    '  function switchTab(tabId) {',
    '    if (tabId === currentTabId) return;',
    '    currentTabId = tabId;',
    '    var data = buildTabData(ALL_FLOWS, tabId, DIRTY_NODE_IDS);',
    '    var els = tabBar.querySelectorAll(".nr-tab");',
    '    for (var i = 0; i < els.length; i++) {',
    '      els[i].classList.toggle("active", els[i].getAttribute("data-tab-id") === tabId);',
    '    }',
    '    groupLayer.selectAll("*").remove();',
    '    linkLayer.selectAll("*").remove();',
    '    nodeLayer.selectAll("*").remove();',
    '    render(data);',
    '    if (zoomState[tabId]) {',
    '      svg.call(zoom.transform, zoomState[tabId]);',
    '    } else {',
    '      svg.call(zoom.transform, d3.zoomIdentity);',
    '    }',
    '  }',
    '',
    '  function refreshCurrentTab() {',
    '    if (!currentTabId) return;',
    '    var data = buildTabData(ALL_FLOWS, currentTabId, DIRTY_NODE_IDS);',
    '    render(data);',
    '  }',
    '',
    '  function refreshTabDirtyIndicators() {',
    '    var els = tabBar.querySelectorAll(".nr-tab");',
    '    for (var i = 0; i < els.length; i++) {',
    '      var tid = els[i].getAttribute("data-tab-id");',
    '      var data = buildTabData(ALL_FLOWS, tid, DIRTY_NODE_IDS);',
    '      var hasDirty = data.nodes.some(function(n) { return n.dirty; });',
    '      els[i].classList.toggle("dirty", hasDirty);',
    '    }',
    '  }',
    '',
    '  function handleNodeDblclick(event, d) {',
    '    event.stopPropagation();',
    '    if (d.type && d.type.indexOf("subflow:") === 0) {',
    '      openSubflowTab(d.type.slice("subflow:".length));',
    '    }',
    '  }',
    '',
    '  function showTooltip(event, d) {',
    '    tooltip.style.display = "block";',
    '    tooltip.innerHTML =',
    '      "<div class=\\"tt-name\\">" + escapeHtml(d.name || d.type) + "</div>" +',
    '      "<div>Type: " + escapeHtml(d.type) + "</div>" +',
    '      "<div>ID: " + escapeHtml(d.id) + "</div>" +',
    '      (d.dirty ? "<div class=\\"tt-dirty\\">\u26a1 Un-deployed changes</div>" : "") +',
    '      (d.d ? "<div>\u26d4 Disabled</div>" : "");',
    '    tooltip.style.left = (event.pageX + 12) + "px";',
    '    tooltip.style.top = (event.pageY - 10) + "px";',
    '  }',
    '',
    '  function hideTooltip() { tooltip.style.display = "none"; }',
    '',
    '  // ---- WebSocket ----',
    '  var WS_URL = (location.protocol === "https:" ? "wss://" : "ws://") + location.host + "/staging-ws";',
    '  var ws = null, reconnectDelay = 3000, reconnectTimer = null;',
    '',
    '  function connectWS() {',
    '    try { ws = new WebSocket(WS_URL); } catch(e) { scheduleReconnect(); return; }',
    '    ws.onopen = function() { banner.classList.remove("visible"); reconnectDelay = 3000; };',
    '    ws.onmessage = function(event) {',
    '      try {',
    '        var msg = JSON.parse(event.data);',
    '        if (msg.type === "staging-update") {',
    '          ALL_FLOWS = msg.flows || [];',
    '          DIRTY_NODE_IDS = new Set(msg.dirtyNodeIds || []);',
    '          var freshTabs = extractTabs(ALL_FLOWS);',
    '          if (freshTabs.length === 0) {',
    '            if (ALL_FLOWS.length > 0) {',
    '              var ntn2 = ALL_FLOWS.filter(function(n) {',
    '                return n.type !== "tab" && n.type !== "group"',
    '                  && Array.isArray(n.wires);',
    '              });',
    '              if (ntn2.length > 0) freshTabs = [{ id: ntn2[0].z || "__default__", name: "Flow", disabled: false, kind: "tab" }];',
    '            }',
    '          }',
    '          reconcileTabs(freshTabs);',
    '          buildTabBar();',
    '          var exists = tabs.some(function(t) { return t.id === currentTabId; });',
    '          if (!exists && tabs.length > 0) { switchTab(tabs[0].id); }',
    '          else { refreshCurrentTab(); }',
    '          refreshTabDirtyIndicators();',
    '        }',
    '      } catch(err) { console.warn("WS parse error:", err); }',
    '    };',
    '    ws.onclose = function() { banner.classList.add("visible"); scheduleReconnect(); };',
    '    ws.onerror = function() {};',
    '  }',
    '',
    '  function scheduleReconnect() {',
    '    if (reconnectTimer) return;',
    '    reconnectTimer = setTimeout(function() {',
    '      reconnectTimer = null;',
    '      connectWS();',
    '      reconnectDelay = Math.min(reconnectDelay * 1.5, 30000);',
    '    }, reconnectDelay);',
    '  }',
    '',
    '  // ---- Refresh button ----',
    '  function applySnapshot(data) {',
    '    ALL_FLOWS = data.flows || [];',
    '    DIRTY_NODE_IDS = new Set(data.dirtyNodeIds || []);',
    '    var freshTabs2 = extractTabs(ALL_FLOWS);',
    '    if (freshTabs2.length === 0) {',
    '      if (ALL_FLOWS.length > 0) {',
    '        var ntn3 = ALL_FLOWS.filter(function(n) { return n.type !== "tab" && n.type !== "group" && Array.isArray(n.wires); });',
    '        if (ntn3.length > 0) freshTabs2 = [{ id: ntn3[0].z || "__default__", name: "Flow", disabled: false, kind: "tab" }];',
    '      }',
    '    }',
    '    reconcileTabs(freshTabs2);',
    '    buildTabBar();',
    '    var exists = tabs.some(function(t) { return t.id === currentTabId; });',
    '    if (!exists && tabs.length > 0) { switchTab(tabs[0].id); }',
    '    else { refreshCurrentTab(); }',
    '    refreshTabDirtyIndicators();',
    '  }',
    '',
    '  btnRefresh.addEventListener("click", function() {',
    '    if (DIRTY_NODE_IDS.size > 0) {',
    '      if (!confirm("Warning: You have un-deployed changes. Refreshing will permanently discard all pending changes. Are you sure you want to continue?")) {',
    '        return;',
    '      }',
    '    }',
    '    btnRefresh.classList.add("loading");',
    '    fetch(\"/staging-refresh\", { method: \"POST\" })',
    '      .then(function(r) { return r.json(); })',
    '      .then(function(data) { applySnapshot(data); btnRefresh.classList.remove("loading"); })',
    '      .catch(function(err) { console.warn("Refresh failed:", err); btnRefresh.classList.remove("loading"); });',
    '  });',
    '',
    '  // ---- Init ----',
    '  buildTabBar();',
    '  if (tabs.length > 0) { switchTab(tabs[0].id); }',
    '  else { currentTabId = "__empty__"; emptyLabel.style("display", "block"); }',
    '  connectWS();',
    '})();',
    '</script>',
    '</body>',
    '</html>'
  ].join('\n');

  return html;
}
